name: Deploy to release server

on:
  push:
    branches: [ "main" ]
    paths:
      - src/backend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - src/backend/**

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy the Docker image to Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          APP_NAME: dogs-companion
        run: |
          docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
